QOSGroup/qos

account/genesis.go, account/genesis_test.go, app/app.go, cmd/qosd/main.go, mapper/BaseMapper.go, mapper/basemapper.go, mapper/basemapper_test.go
=> 创建app，init,start

account/account.go, txs/transfer.go
QOSAccount增加NewQOSAccount方法，初始化qos为0
transfer tx GetSignData qos nil导致的签名问题
=> 关于 qos nil 的两处修改

cmd/approve/approvecli.go, cmd/transfer/transfercli.go, go.mod, txs/approve/approve.go, txs/approve/approve_test.go, txs/createqsc.go, txs/issueqsc.go, txs/transfer.go, txs/transfer_test.go
qbase 依赖版本v0.06
func ValidateData 返回值 bool 改成 error
=> 更改ValidateData返回值

txs/transfer/client/transfer.go, types/util.go
=> fix-65:qoscli tx transfer 负值 index out of range

docs/client/approve.md, txs/approve/client/approve.go
=> 查询不存在的approve时返回不存在提示

app/genesis.go, cmd/qosd/main.go, cmd/qosd/testnet/testnet.go, docs/install/networks.md
=> qosd testnet cmd

docs/client/transfer.md, txs/transfer/client/transfer.go
=> 更新senders、receivers多个账户提示

app/codec.go, cmd/qoscli/main.go, docs/.vuepress/config.js, docs/client/qcp.md, docs/client/qsc.md, docs/spec/txs/qcp.md, docs/spec/txs/qsc.md, go.mod, txs/codec.go, txs/qcp/client/cmd.go, txs/qcp/client/qcp.go, txs/qcp/codec.go, txs/qcp/qcp.go, txs/qsc/client/qsc.go, txs/qsc/mapper.go, txs/qsc/qsc.go, types/qsc.go
=> create qsc 拆分出create qsc 和 init qcp

account/account.go, account/account_test.go, cmd/qosd/init/genesis_accts.go, cmd/qosd/init/util.go, cmd/qosd/testnet/testnet.go
=> update QOSAccount and tests

cmd/qosd/testnet/testnet.go, txs/staking/validator.go, types/config.go
1. genesis.json validators不能为空
2. revoke validaotr 时间不对
=> testnet and revoke validator bugs

txs/staking/client/cmd.go, txs/staking/client/query.go, txs/staking/vote_info_mapper.go, types/vote_info.go
=> 增加valiadtor在投票窗口未投票信息集合

app/genesis.go, cmd/qoscli/main.go, cmd/qosd/init/init.go, cmd/qosd/init/util.go, cmd/qosd/main.go, cmd/qosd/testnet/testnet.go, go.mod, txs/qcp/client/qcp.go, txs/qsc/client/qsc.go
update init command
适配JSON格式证书
qoscli add config command
=> update commands and ca

cmd/qosd/init/validator.go, docs/client/qoscli.md, docs/client/qosd.md, docs/install/networks.md, docs/install/testnet.md, docs/install/testnet/fullnode.md, docs/install/testnet/validator.md, docs/spec/genesis.md, docs/spec/validators/all_about_validators.md, module/stake/client/validator.go
=> remove pubkey flag in create validator cmd

Dockerfile
修改了原本repo中的 Dockerfile，在连接外网的网络环境下
docker build -t qos-node . //编译
docker save qos-node -o qos-node //导出镜像
docker excu -itd qos-node //执行镜像
docker contaner ls //列出镜像号
docker attach 载入
配置参数，加入主网
=> [fix]: fix docker build method

app/app.go, app/genesis.go, module/gov/abci.go, module/gov/codec.go, module/gov/errors.go, module/gov/genesis.go, module/gov/mapper.go, module/gov/mapper_keys.go, module/gov/params.go, module/gov/tags.go, module/gov/tally.go, module/gov/txs_deposit.go, module/gov/txs_proposal.go, module/gov/txs_vote.go, module/gov/types/deposit.go, module/gov/types/proposal.go, module/gov/types/vote.go, types/util.go
=> qos governance

cmd/qosd/init/flags.go, cmd/qosd/init/gentx.go, cmd/qosd/init/testnet.go, docs/command/qoscli.md, docs/command/qosd.md, docs/i18n/en/install/testnet/validator.md, docs/install/networks.md, docs/install/testnet.md, docs/spec/genesis.md, docs/spec/staking.md, docs/spec/validators/all_about_validators.md, module/eco/types/validator.go, module/gov/mapper_test.go, module/gov/tally_test.go, module/stake/abci_test.go, module/stake/client/cmd.go, module/stake/client/query.go, module/stake/client/validator.go, module/stake/codec.go, module/stake/genesis.go, module/stake/tags.go, module/stake/txs_validator.go
=> 添加validator编辑功能

cmd/qosd/init/testnet.go, docs/command/qosd.md
=> add guardians in qosd testnet command

module/gov/genesis.go
=> fix Issue #237

module/gov/abci.go
=> fix Issue 238

docs/spec/governance.md, module/gov/mapper.go, module/gov/mapper_test.go, module/gov/params.go, module/gov/txs_proposal.go
=> min_proposer_deposit_rate and burn_rate parametrization

module/distribution/mapper/hooks.go, module/stake/mapper/delegation.go, module/stake/mapper/hooks.go, module/stake/types/hooks.go
unbond and redelegate error
fix #254
=> module structure refactor

module/distribution/abci.go, module/stake/txs/validator.go
=> compound delegation error

module/approve/types/approve.go, module/distribution/mapper/invariant.go, module/qsc/mapper/invariant.go, module/qsc/module.go, module/qsc/txs/txs.go, module/qsc/types/qsc.go, types/util.go
=> fix invariant check bugs in distribution and qsc

module/distribution/abci.go, module/distribution/mapper/invariant.go, module/stake/mapper/validator.go
=> fix #314 #315 

cmd/qosd/init/account.go, cmd/qosd/init/flags.go, cmd/qosd/init/testnet.go, cmd/qosd/main.go, module/bank/abci.go, module/bank/abci_test.go, module/bank/alias.go, module/bank/client/cmd.go, module/bank/client/query.go, module/bank/genesis.go, module/bank/mapper/mapper.go, module/bank/module.go, module/bank/types/genesis.go
=> lock account

cmd/qosd/init/flags.go, cmd/qosd/init/gentx.go, cmd/qosd/init/testnet.go, module/stake/alias.go, module/stake/client/validator.go, module/stake/genesis.go, module/stake/txs/validator.go
=> gentx support delegations

app/app.go, module/gov/abci.go, module/gov/mapper/mapper.go, module/gov/mapper/mapper_test.go, module/gov/mapper/tally.go, module/gov/txs/proposal.go, module/gov/types/genesis.go, module/gov/types/params.go, module/gov/types/proposal.go
=> proposal levels

module/gov/genesis.go
=> gov params init bug

module/approve/client/approve.go, module/approve/txs/txs.go, module/bank/client/transfer.go, module/bank/txs/transfer.go, module/gov/client/proposal.go, module/gov/client/vote.go, module/gov/txs/proposal.go, module/gov/txs/vote.go, module/guardian/client/guardian.go, module/guardian/txs/txs.go, module/qcp/client/qcp.go, module/qcp/txs/txs.go, module/qsc/client/qsc.go, module/qsc/txs/txs.go, module/stake/client/validator.go, module/stake/txs/validator.go
=> 合并cli和itx输入校验逻辑

module/stake/client/query.go
=>  验证节点查询增加自绑定信息
